# Generated by Django 5.2.7 on 2026-06-05 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoDetalle',
            fields=[
                ('IdFoto', models.AutoField(db_column='IdFoto', primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='inspecciones/fotos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FotoDetalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('CodigoUbicacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CodigoInterno', models.CharField(max_length=50)),
                ('CodigoTipoElemento', models.CharField(max_length=2)),
                ('Medidas', models.CharField(max_length=50)),
                ('DireccionComercial', models.CharField(max_length=200)),
                ('DireccionReal', models.CharField(max_length=200)),
                ('CodigoDepartamento', models.CharField(max_length=2)),
                ('CodigoProvincia', models.CharField(max_length=2)),
                ('CodigoDistrito', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'UBICACIONES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubigeo2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoDepartamento', models.CharField(max_length=2)),
                ('CodigoProvincia', models.CharField(max_length=2)),
                ('CodigoDistrito', models.CharField(max_length=2)),
                ('Nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UBIGEO2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InspeccionCampo',
            fields=[
                ('NumeroRegistro', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('FechaInspeccion', models.DateField()),
                ('ZonaInspeccion', models.CharField(max_length=2)),
                ('CodigoResponsable', models.CharField(blank=True, max_length=20, null=True)),
                ('UsuarioCreacion', models.CharField(max_length=30)),
                ('FechaCreacion', models.DateField()),
                ('EstadoRegistro', models.CharField(default='00', max_length=2)),
            ],
            options={
                'db_table': 'InspeccionCampo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InspeccionCampoDetalle',
            fields=[
                ('IdDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoElementoRef', models.CharField(max_length=20)),
                ('Ubicacion', models.CharField(max_length=50, null=True)),
                ('CodigoDepartamento', models.CharField(max_length=2)),
                ('CodigoProvincia', models.CharField(max_length=2)),
                ('CodigoDistrito', models.CharField(max_length=2)),
                ('EstadoElemento', models.CharField(max_length=2, null=True)),
                ('PuntoLuz', models.BooleanField(null=True)),
                ('NumeroReflectores', models.IntegerField(null=True)),
                ('EstadoReflectores', models.CharField(max_length=2, null=True)),
                ('PublicidadLona', models.CharField(max_length=2, null=True)),
                ('ControlPublicidad', models.CharField(max_length=2, null=True)),
                ('EstadoLona', models.CharField(max_length=2, null=True)),
                ('EstadoLogo', models.CharField(max_length=2, null=True)),
                ('Observaciones', models.CharField(max_length=500, null=True)),
                ('NumeroRegistro', models.ForeignKey(db_column='NumeroRegistro', on_delete=django.db.models.deletion.PROTECT, to='dashboard.inspeccioncampo')),
            ],
            options={
                'db_table': 'InspeccionCampoDetalle',
                'managed': True,
            },
        ),
    ]
