# Generated by Django 5.2.7 on 2026-05-19 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccioncampodetalle',
            name='CodigoDepartamento',
            field=models.CharField(default=123456, max_length=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FotoDetalle',
            fields=[
                ('IdFoto', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='inspecciones/fotos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(db_column='IdDetalle', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='dashboard.inspeccioncampodetalle')),
            ],
            options={
                'db_table': 'FotoDetalle',
                'managed': True,
            },
        ),
    ]
